feat(task 3): add get and count methods to  DBStorage and FileStorage
haoningng/holbertonschool-AirBnB_clone_v3 pull request #1
Opened 2024-04-16 02:36 UTC by Goaty-yagi

2024-04-16 09:13 UTC, haoningng requested changes

2024-04-16 09:13 UTC, haoningng commented on models/engine/file_storage.py
> +            return obj_count
There is nothing wrong here, but there is room for improvement. 
This whole `if cls:` block can probably be simplified by utilising the class-specific all method 
```python
if cls:
            return len(self.all(cls))
```

2024-04-16 09:13 UTC, haoningng commented on models/engine/file_storage.py
> +            filtered_list = [value for value in all_obj.values() if value.id == id]
This line is too long (83 > 79 characters). It fails pycodestyle check. Might need to split it into two lines

2024-04-16 09:13 UTC, haoningng commented on api/v1/app.py
> +    app.run(host='0.0.0.0', port=5000, threaded=False)
I believe the threaded parameter should be set to True instead as required by the task:
<img width="720" alt="Screenshot 2024-04-16 at 6 59 51 PM" src="https://github.com/haoningng/holbertonschool-AirBnB_clone_v3/assets/65799500/dcd6be60-8263-48a2-a5fc-cacee3bab52f">

2024-04-16 10:32 UTC, haoningng requested changes

2024-04-16 10:32 UTC, haoningng commented on api/v1/views/states.py
> +    return jsonify(state.to_dict())
Actually I think we need to specify the status code to be 201 , otherwise it will return status code 200 by default.
<img width="472" alt="Screenshot 2024-04-16 at 8 28 58 PM" src="https://github.com/haoningng/holbertonschool-AirBnB_clone_v3/assets/65799500/77733b9a-2e77-4116-a8da-b29e41a35414">
One way to do it is this
```python
from flask import Flask, jsonify, make_response
...
def create_state():
....
    # Create a JSON response with a custom status code
    response_data = state.to_dict()
    status_code = 201 

    # Use make_response to create a response with custom data and status code
    response = make_response(jsonify(response_data), status_code)

    return response
```

2024-04-16 11:17 UTC, Goaty-yagi commented
Thank you for your code review.
did you code review all my push but not only PR?

2024-04-16 11:27 UTC, haoningng commented
> Thank you for your code review.
> did you code review all my push but not only PR?

Yeah I have reviewed everything you have pushed so far I think. Which is up until task 7. Not much to change though. 👍

2024-04-16 11:29 UTC, Goaty-yagi reviewed
test is done!
PR author can't approve and request changes!

2024-04-16 11:29 UTC, Goaty-yagi commented on models/engine/db_storage.py
> +        return obj_count
**Test to comment on changes.**

2024-04-16 12:51 UTC, Goaty-yagi commented
I wonder if my changes after PR will be included in the PR.

2024-04-16 21:30 UTC, merged

2024-04-16 21:32 UTC, haoningng commented
> I wonder if my changes after PR will be included in the PR.

Yeah looks like they are all included in the PR, I have merged all 7 commits to the Master branch 👍

2024-04-17 00:13 UTC, Goaty-yagi commented
I see, I started to understand what it looks like.